data_dir: 'data'
preprocessed_dir: 'data/preprocessed'
target_dir: 'data/save'
model_path: 'google/flan-t5-base'
model_size: 'base'
no_label: "neutral"
label_list:  ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
emb_dim: 300
instruct: None    # "What emotion causes '{target}' towards the last conversation utterance?"
                  # "What emotion state is expressed in '{target}'?"
output_channels: 100
speaker_emb_dims: 300
project_dims: 300
max_length: 300
train_mode: random
filters: [3,4,5]
dropout: 0.5
shuffle: True
bert_lr: 2e-4
patience: 100
max_grad_norm: 1.0
warmup_proportion: 0.1
gradient_accumulation_steps: 1
adam_epsilon: 1e-8
warmup_steps: 0
weight_decay: 0.01
seed: 42
debug: False
